Set up CI with Azure Pipelines
[skip ci]

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,49 +1,40 @@
-# Source: https://dev.to/ganesshkumar/pi-hole-in-azure-container-instances-4abf
+#!/bin/bash
 
-# Download  Azure CLI optionally
-#Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
+# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
 
-cd $PSScriptRoot
+PIHOLE_BASE="${PIHOLE_BASE:-$(pwd)}"
+[[ -d "$PIHOLE_BASE" ]] || mkdir -p "$PIHOLE_BASE" || { echo "Couldn't create storage directory: $PIHOLE_BASE"; exit 1; }
 
-$subscriptionId = "1231321332144" # shown after logging in with 'az login'
+# Note: ServerIP should be replaced with your external ip.
+docker run -d \
+    --name pihole \
+    -p 53:53/tcp -p 53:53/udp \
+    -p 80:80 \
+    -p 443:443 \
+    -e TZ="America/Chicago" \
+    -v "${PIHOLE_BASE}/etc-pihole/:/etc/pihole/" \
+    -v "${PIHOLE_BASE}/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
+    --dns=127.0.0.1 --dns=1.1.1.1 \
+    --restart=unless-stopped \
+    --hostname pi.hole \
+    -e VIRTUAL_HOST="pi.hole" \
+    -e PROXY_LOCATION="pi.hole" \
+    -e ServerIP="127.0.0.1" \
+    pihole/pihole:latest
 
-$rgName = "rg-pi-hole"
-$location = "WestEurope" # use 'az account list-locations' to list all locations
-$storageName = "piholestorage"
-$containerGroupName = "pi-hole-container-group"
-$containerName = "pi-hole-container"
-$yamlOriginalFileName = "deploy-pi-hole-original.yaml"
-$yamlModifiedFileName = "deploy-pi-hole.yaml"
-$customDnsName = "pihole"
-$webPassword = "superSecretLongAndCrazyPass22..334"
+printf 'Starting up pihole container '
+for i in $(seq 1 20); do
+    if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
+        printf ' OK'
+        echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: https://${IP}/admin/"
+        exit 0
+    else
+        sleep 3
+        printf '.'
+    fi
 
-az login
-az account set --subscription $subscriptionId
-az group create --name $rgName --location $location
-az storage account create --resource-group $rgName --name $storageName --location $location --sku Standard_LRS
-az storage share create --account-name $storageName --name etc-pihole
-az storage share create --account-name $storageName --name etc-dnsmasq
-
-$STORAGE_KEY=$(az storage account keys list --resource-group $rgName --account-name $storageName --query "[0].value" --output tsv)
-
-# prepare yaml file
-$stringsToReplace = @(
-    @("<location>", $location),
-    @("<container_group_name>", $containerGroupName),
-    @("<container_name>", $containerName),
-    @("<custom_large_string>", $webPassword),
-    @("<custom_dnsname>", $customDnsName),
-    @('<value of $STORAGE_KEY>', $STORAGE_KEY),
-    @('<storage_name>', $storageName)
-)
-
-Copy-Item -Path $yamlOriginalFileName -Destination $yamlModifiedFileName
-
-# Replacing all placeholder in the yaml file
-foreach($replace in $stringsToReplace){
-    (Get-Content $yamlModifiedFileName).replace($replace[0], $replace[1]) | Set-Content $yamlModifiedFileName
-}
-
-az container create --resource-group $rgName --file $yamlModifiedFileName
-
-az container show --resource-group $rgName --name $containerGroupName --query ipAddress.ip --output tsv
+    if [ $i -eq 20 ] ; then
+        echo -e "\nTimed out waiting for Pi-hole start, consult check your container logs for more info (\`docker logs pihole\`)"
+        exit 1
+    fi
+done;
